import type { LoopPose } from "./types.js";

export type LoopVariant = "small" | "home";
export type LoopFrame = "blink" | "bob";

export const SIZES: Readonly<Record<LoopVariant, { readonly w: number; readonly h: number }>> = {
  small: { w: 18, h: 14 },
  home: { w: 32, h: 20 },
};

export const PALETTE: Readonly<Record<string, { readonly deep: string; readonly cube: string }>> = {
  o: { deep: "#7a2a48", cube: "#5f005f" },
  G: { deep: "#c9486f", cube: "#af5f87" },
  g: { deep: "#e86a8e", cube: "#d75f87" },
  h: { deep: "#f7a3bc", cube: "#ffafd7" },
  S: { deep: "#d9776f", cube: "#d78787" },
  s: { deep: "#f2918c", cube: "#ff8787" },
  l: { deep: "#f8b3a6", cube: "#ffafaf" },
  c: { deep: "#fcd6c6", cube: "#ffd7d7" },
  k: { deep: "#241230", cube: "#1c1c1c" },
  p: { deep: "#6a3380", cube: "#5f0087" },
  w: { deep: "#ffffff", cube: "#ffffff" },
  r: { deep: "#ec6f86", cube: "#ff5f87" },
  m: { deep: "#8e2f4e", cube: "#87005f" },
  t: { deep: "#c8425f", cube: "#d7005f" },
  n: { deep: "#0d223d", cube: "#00005f" },
  N: { deep: "#23416b", cube: "#000087" },
  a: { deep: "#e84d8a", cube: "#ff0087" },
};

export const LOOP_ART: Readonly<
  Record<LoopPose, Readonly<Record<LoopVariant, readonly string[]>>>
> = {
  idle: {
    home: [
      "..oo........................oo..",
      ".ohgoo....................oogho.",
      ".ohhggoo................oogghho.",
      "..ooggGGoo.oooooooooo.ooGGggoo..",
      "....ooGGGoollllllllllooGGGoo....",
      "oo.....oolllllllllllllloo.....oo",
      "ohggoo.oSllllllllllllllSo.ooggho",
      "ohhhggGoSskkllllllllkksSoGgghhho",
      ".ooGGGGoSkwkksssssskwkkSoGGGGoo.",
      "...oooooSkkpksssssskkpkSooooo...",
      ".....oooSkppksssssskppkSooo.....",
      "..oohgoSsskksssssssskkssSoghoo..",
      ".ohhggoSrrssmssssssmssrrSogghho.",
      ".oGGoo.oSssssmmmmmmssssSo.ooGGo.",
      "..oo....ooSssssssssssSoo....oo..",
      "..........ooSSSSSSSSoo..........",
      "....ooooonnnnNNnNnNNnnnooooo....",
      "...osssonnnnnnNnNnNnnnnnossso...",
      "...ossSonnnnnnnnNnnnannnoSsso...",
      "...osSSonnnnnnnnNnnnnnnnoSSso...",
    ],
    small: [
      ".o..............o.",
      "ohgo..........ogho",
      ".ohgGooooooooGgho.",
      "..oGoollllllooGo..",
      "oo.ollllllllllo.oo",
      "hggoSllllllllSoggh",
      ".oGoSwksssswkSoGo.",
      "..oSskpsssskpsSo..",
      "ohoSsssmssmsssSoho",
      ".oGooSssmmssSooGo.",
      "..o..ooSSSSoo..o..",
      "...ooonnNnnnooo...",
      "..osSonnNnnnoSso..",
      "..oSSonnNnnnoSSo..",
    ],
  },
  thinking: {
    home: [
      "..oo........................oo..",
      ".ohgoo....................oogho.",
      ".ohhggoo................oogghho.",
      "..ooggGGoo.oooooooooo.ooGGggoo..",
      "....ooGGGoollllllllllooGGGoo....",
      "oo.....oollmmlllllllllloo.....oo",
      "ohggoo.oSmmllllllllllllSo.ooggho",
      "ohhhggGoSskkllllllllllsSoGgghhho",
      ".ooGGGGoSkwkkssssssmmmmSoGGGGoo.",
      "...oooooSkkpksssssskkpkSooooo...",
      ".....oooSkppksssssskppkSooo.....",
      "..oohgoSsskksssssssskkssSoghoo..",
      ".ohhggoSssssssssssmsssssSogghho.",
      ".oGGoo.oSssssssmmmsssssSo.ooGGo.",
      "..oo....ooSssssssssssSoo....oo..",
      "..........ooSSSSSSSSoo..........",
      "....ooooonnnnNNnNnNNnnnooooo....",
      "...osssonnnnnnNnNnNnnnnnossso...",
      "...ossSonnnnnnnnNnnnannnoSsso...",
      "...osSSonnnnnnnnNnnnnnnnoSSso...",
    ],
    small: [
      ".o..............o.",
      "ohgo..........ogho",
      ".ohgGooooooooGgho.",
      "..oGoollllllooGo..",
      "oo.ollmlllllllo.oo",
      "hggoSllllllllSoggh",
      ".oGoSwkssssmmSoGo.",
      "..oSskpsssskpsSo..",
      "ohoSssssssmsssSoho",
      ".oGooSssmmssSooGo.",
      "..o..ooSSSSoo..o..",
      "...ooonnNnnnooo...",
      "..osSonnNnnnoSso..",
      "..oSSonnNnnnoSSo..",
    ],
  },
  impressed: {
    home: [
      "..oo.......a...........a....oo..",
      ".ohgoo......a.........a...oogho.",
      ".ohhggoo................oogghho.",
      "..ooggGGoo.oooooooooo.ooGGggoo..",
      "....ooGGGoollllllllllooGGGoo....",
      "oo.....oolllllllllllllloo.....oo",
      "ohggoo.oSllllllllllllllSo.ooggho",
      "ohhhggGoSskkllllllllkksSoGgghhho",
      ".ooGGGGoSkwkksssssskwkkSoGGGGoo.",
      "...oooooSkkpwsssssskkpwSooooo...",
      ".....oooSkppksssssskppkSooo.....",
      "..oohgoSsskksssssssskkssSoghoo..",
      ".ohhggoSrrssmmmmmmmmssrrSogghho.",
      ".oGGoo.oSssssmttttmssssSo.ooGGo.",
      "..oo....ooSsssmmmmsssSoo....oo..",
      "..........ooSSSSSSSSoo..........",
      "....ooooonnnnNNnNnNNnnnooooo....",
      "...osssonnnnnnNnNnNnnnnnossso...",
      "...ossSonnnnnnnnNnnnannnoSsso...",
      "...osSSonnnnnnnnNnnnnnnnoSSso...",
    ],
    small: [
      ".o..............o.",
      "ohgo..........ogho",
      ".ohgGooooooooGgho.",
      "..oGoollllllooGo..",
      "oo.ollllllllllo.oo",
      "hggoSllllllllSoggh",
      ".oGoSwksssswkSoGo.",
      "..oSskwsssskwsSo..",
      "ohoSsssmmmmsssSoho",
      ".oGooSssttssSooGo.",
      "..o..ooSSSSoo..o..",
      "...ooonnNnnnooo...",
      "..osSonnNnnnoSso..",
      "..oSSonnNnnnoSSo..",
    ],
  },
  facepalm: {
    home: [
      "..oo........................oo..",
      ".ohgoo....................oogho.",
      ".ohhggoo................oogghho.",
      "..ooggGGoo.oooooooooo.ooGGggoo..",
      "....ooGGGoollllllllllooGGGoo....",
      "oo.....oolllllllllllllloo.....oo",
      "ohggoo.oSllllllllllllllSo.ooggho",
      "ohhhggGoSsllllllllololoSoGgghhho",
      ".ooGGGGoSssssssssosososooGGGGoo.",
      "...oooooSmmmmssssossssssooooo...",
      ".....oooSkkpkssssosssssSooo.....",
      "..oohgoSsskksssssosssssSooghoo..",
      ".ohhggoSssssssssssoSSSSoSogghho.",
      ".oGGoo.oSsssmmmmssssoSSoo.ooGGo.",
      "..oo....ooSsssssssssoSSo....oo..",
      "..........ooSSSSSSSSooSSo.......",
      "....ooooonnnnNNnNnNNnoSSoooo....",
      "...osssonnnnnnNnNnNnnnnnossso...",
      "...ossSonnnnnnnnNnnnannnoSsso...",
      "...osSSonnnnnnnnNnnnnnnnoSSso...",
    ],
    small: [
      ".o..............o.",
      "ohgo..........ogho",
      ".ohgGooooooooGgho.",
      "..oGoolllloloooo..",
      "oo.ollllllsosos.oo",
      "hggoSlllllssssSogh",
      ".oGoSmmsssoSSSoGo.",
      "..oSskpssssoSSoo..",
      "ohoSssssssssoSooho",
      ".oGooSsmmsssSooGo.",
      "..o..ooSSSSoo..o..",
      "...ooonnNnnnooo...",
      "..osSonnNnnnoSso..",
      "..oSSonnNnnnoSSo..",
    ],
  },
  celebrating: {
    home: [
      "..oo.......a...........a....oo..",
      ".ohgoo......a.........a...oogho.",
      ".ohhggoo................oogghho.",
      "..ooggGGoo.oooooooooo.ooGGggoo..",
      "....ooGGGoollllllllllooGGGoo....",
      "oo.....oolllllllllllllloo.....oo",
      "ohggoo.oSllllllllllllllSo.ooggho",
      "ohhhggGoSsllllllllllllsSoGgghhho",
      ".ooGGGGoSskksssssssskksSoGGGGoo.",
      "...oooooSksskssssssksskSooooo...",
      ".....oooSssssssssssssssSooo.....",
      "..oohgoSssssssssssssssssSoghoo..",
      ".ohhggoSrrssmmmmmmmmssrrSogghho.",
      ".oGGoo.oSssssmttttmssssSo.ooGGo.",
      "..oo....ooSsssmmmmsssSoo....oo..",
      "..........ooSSSSSSSSoo..........",
      "....ooooonnnnNNnNnNNnnnooooo....",
      "...osssonnnnnnNnNnNnnnnnossso...",
      "...ossSonnnnnnnnNnnnannnoSsso...",
      "...osSSonnnnnnnnNnnnnnnnoSSso...",
    ],
    small: [
      ".o..............o.",
      "ohgo..........ogho",
      ".ohgGooooooooGgho.",
      "..oGoollllllooGo..",
      "oo.ollllllllllo.oo",
      "hggoSllllllllSoggh",
      ".oGoSskssssksSoGo.",
      "..oSskssssssksSo..",
      "ohoSsssmmmmsssSoho",
      ".oGooSssttssSooGo.",
      "..o..ooSSSSoo..o..",
      "...ooonnNnnnooo...",
      "..osSonnNnnnoSso..",
      "..oSSonnNnnnoSSo..",
    ],
  },
  sleeping: {
    home: [
      "................................",
      "..oo........................oo..",
      ".ohgoo....................oogho.",
      ".ohhggoo...oooooooooo...oogghho.",
      "..ooggGGooolllllllllloooGGggoo..",
      "....ooGGolllllllllllllloGGoo....",
      "oo.....oSllllllllllllllSo.....oo",
      "ohggoo.oSsllllllllllllsSo.ooggho",
      "ohhhggGoSssssssssssssssSoGgghhho",
      ".ooGGGGoSksskssssssksskSoGGGGoo.",
      "...oooooSskksssssssskksSooooo...",
      ".....ooSssssssssssssssssSoo.....",
      "..oohgoSssssssssssssccssSoghoo..",
      ".ohhggGoSssssssmmsscscsSoGgghho.",
      ".oGGoo..ooSsssssssssccoo..ooGGo.",
      "..oo......ooSSSSSSSSoo......oo..",
      "....ooooonnnnNNnNnNNnnnooooo....",
      "...osssonnnnnnNnNnNnnnnnossso...",
      "...ossSonnnnnnnnNnnnannnoSsso...",
      "...osSSonnnnnnnnNnnnnnnnoSSso...",
    ],
    small: [
      "..................",
      ".o..............o.",
      "ohgo..oooooo..ogho",
      ".ohgoolllllloogho.",
      "..oolllllllllloo..",
      "oo.oSllllllllSo.oo",
      "hggoSssssssssSoggh",
      ".ooSskksssskksSoo.",
      "..oSssssssssssSo..",
      "ohgooSsssmscSoogho",
      ".oGo.ooSSSSoo.oGo.",
      "..oooonnNnnnoooo..",
      "..osSonnNnnnoSso..",
      "..oSSonnNnnnoSSo..",
    ],
  },
};

export const IDLE_FRAMES: Readonly<
  Record<LoopVariant, Readonly<Record<LoopFrame, readonly string[]>>>
> = {
  home: {
    blink: [
      "..oo........................oo..",
      ".ohgoo....................oogho.",
      ".ohhggoo................oogghho.",
      "..ooggGGoo.oooooooooo.ooGGggoo..",
      "....ooGGGoollllllllllooGGGoo....",
      "oo.....oolllllllllllllloo.....oo",
      "ohggoo.oSllllllllllllllSo.ooggho",
      "ohhhggGoSsllllllllllllsSoGgghhho",
      ".ooGGGGoSssssssssssssssSoGGGGoo.",
      "...oooooSssssssssssssssSooooo...",
      ".....oooSkkkksssssskkkkSooo.....",
      "..oohgoSssssssssssssssssSoghoo..",
      ".ohhggoSrrssmssssssmssrrSogghho.",
      ".oGGoo.oSssssmmmmmmssssSo.ooGGo.",
      "..oo....ooSssssssssssSoo....oo..",
      "..........ooSSSSSSSSoo..........",
      "....ooooonnnnNNnNnNNnnnooooo....",
      "...osssonnnnnnNnNnNnnnnnossso...",
      "...ossSonnnnnnnnNnnnannnoSsso...",
      "...osSSonnnnnnnnNnnnnnnnoSSso...",
    ],
    bob: [
      "................................",
      "..oo........................oo..",
      ".ohgoo....................oogho.",
      ".ohhggoo...oooooooooo...oogghho.",
      "..ooggGGooolllllllllloooGGggoo..",
      "....ooGGolllllllllllllloGGoo....",
      "oo.....oSllllllllllllllSo.....oo",
      "ohggoo.oSskkllllllllkksSo.ooggho",
      "ohhhggGoSkwkksssssskwkkSoGgghhho",
      ".ooGGGGoSkkpksssssskkpkSoGGGGoo.",
      "...oooooSkppksssssskppkSooooo...",
      ".....ooSsskksssssssskkssSoo.....",
      "..oohgoSrrssmssssssmssrrSoghoo..",
      ".ohhggGoSssssmmmmmmssssSoGgghho.",
      ".oGGoo..ooSssssssssssSoo..ooGGo.",
      "..oo......ooSSSSSSSSoo......oo..",
      "....ooooonnnnNNnNnNNnnnooooo....",
      "...osssonnnnnnNnNnNnnnnnossso...",
      "...ossSonnnnnnnnNnnnannnoSsso...",
      "...osSSonnnnnnnnNnnnnnnnoSSso...",
    ],
  },
  small: {
    blink: [
      ".o..............o.",
      "ohgo..........ogho",
      ".ohgGooooooooGgho.",
      "..oGoollllllooGo..",
      "oo.ollllllllllo.oo",
      "hggoSllllllllSoggh",
      ".oGoSssssssssSoGo.",
      "..oSskksssskksSo..",
      "ohoSsssmssmsssSoho",
      ".oGooSssmmssSooGo.",
      "..o..ooSSSSoo..o..",
      "...ooonnNnnnooo...",
      "..osSonnNnnnoSso..",
      "..oSSonnNnnnoSSo..",
    ],
    bob: [
      "..................",
      ".o..............o.",
      "ohgo..oooooo..ogho",
      ".ohgoolllllloogho.",
      "..oolllllllllloo..",
      "oo.oSllllllllSo.oo",
      "hggoSwksssswkSoggh",
      ".ooSskpsssskpsSoo.",
      "..oSsssmssmsssSo..",
      "ohgooSssmmssSoogho",
      ".oGo.ooSSSSoo.oGo.",
      "..oooonnNnnnoooo..",
      "..osSonnNnnnoSso..",
      "..oSSonnNnnnoSSo..",
    ],
  },
};
